### ISSUE TITLE
touchSnag doesn't work when a pointer is already down during reset

### ISSUE THREAD

**Issue by phet-steele** [phetsims/charges-and-fields#49] opened 2015-06-24 19:20 UTC
1. While holding a charge (or other object/tool) with one finger (Finger A), press the reset all button with another finger (Finger B).
2. Never let up on Finger A.
3. With Finger B, drag out another object from its bin.
4. Place this new object in the play area, and notice while moving Finger A over this new object, it does not get picked up.

After maybe 50 minutes of messing with this issue, I've only seen twice that a charge I'm dragging with Finger B will jump to Finger A. This was the reason I was testing this issue for so long, but couldn't come up with any reproducibility. This video begins with showing the correct behavior of a charge being grabbed by dragging your finger over it, then how the charge is not grabbed after the reset:

https://drive.google.com/file/d/0B3HJopSo_QqLbC15MXNrb1R2aXM/view?usp=sharing

Tested on iPad Air 2

**Comment by phet-steele** [comment] 2015-06-24 19:20
Troubleshooting information (do not edit):
Name: Charges And Fields
URL: http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-rc.1/charges-and-fields_en.html
Version: 1.0.0-rc.1 2015-06-22 16:50:22 UTC
Features missing: fullscreen
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (iPad; CPU OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F69 Safari/600.1.4
Language: en-us
Window: 768x928
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Apple A8X GPU - 53.13)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"comment":"# charges-and-fields 1.0.0-rc.1 Mon Jun 22 2015 12:50:20 GMT-0400 (Est (heure d’été))","assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"master"},"axon":{"sha":"f4996f9d182deb1b9e799c9ec6282bf8dcfa43bc","branch":"master"},"babel":{"sha":"2431e7111ee0aa3d3eedef3727972abc78b6c1f1","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"master"},"charges-and-fields":{"sha":"8fda05bfceb548a583cc0f84ac42afc36914bd44","branch":"1.0"},"chipper":{"sha":"bed81ebb33ae6b02bfd1459e9a8697ba607738ca","branch":"master"},"dot":{"sha":"6fe16dea5cf6243033eff851ac67a9dfe5d77c4c","branch":"master"},"joist":{"sha":"1862e60794889b4f7297cb00c79639eaffd556d2","branch":"master"},"kite":{"sha":"9d2a34ddcb9258544a02afdc65f9632348fd7b73","branch":"master"},"phet-core":{"sha":"328c6e2f6df1ee3da1bdd41877d2113cfc1e4a71","branch":"master"},"phetcommon":{"sha":"48b8119d27954452d6d8e015ac7ed9c044261285","branch":"master"},"scenery":{"sha":"61011f28042e8960fd9ed43bf3d3f1e1c38826a1","branch":"master"},"scenery-phet":{"sha":"ea0e0d835c72338dd5c88d52473759125eb95ee1","branch":"master"},"sherpa":{"sha":"ab46b0d5ffaf945e58a32759b558af017dcfc63a","branch":"master"},"sun":{"sha":"cec7fc906bdb209ba0938760f2e60eb25a59912d","branch":"master"}}

**Comment by veillette** [comment] 2015-06-28 15:44
Thanks @phet-steele for a very well written ticket.. The video is very useful to illustrate the problem. 

As far as how to go about fixing this issue, I would need  to entrust it to @jonathanolson if we need a fix since I don't know how to address it. 

However before we go down this route, I will reassign to @ariel-phet to establish the priority of this bug. On one hand, this bug is a fairly minor annoyance under a somewhat contrived scenario. On the other hand this is most likely affecting all sims that make uses of multi-touch.

**Comment by veillette** [comment] 2015-06-28 15:50
FYI, I was able to reproduce this issue in Least-squares-regression

**Comment by ariel-phet** [comment] 2015-07-13 23:49
Not important to fix for charges and fields, but a very nice catch @phet-steele. I will close this issue and move the report over to a scenery issue.

**Comment by ariel-phet** [comment] 2015-07-13 23:53
Closing, moved to https://github.com/phetsims/scenery/issues/447

**Closed as completed by ariel-phet** 2015-07-13 23:53 UTC
Labels: type:multitouch
