### ISSUE TITLE
Occasional, less responsive dragging of value labels

### ISSUE THREAD

**Issue by phet-steele** [phetsims/charges-and-fields#65] opened 2015-08-24 18:11 UTC
First off, my guess is this will be very hard to reproduce. Every once and a while, the value labels for the equipotential lines will be very difficult to drag. My assumption is that this happens more often in small circles, but I've still seen it it larger, more complex equipotential lines, too. This video shows a relatively simple set up where I could make it happen pretty easily. Note in the video that the value on the smallest circle (closest to the positive charge) gets much harder to drag after I add the third equipotential line (sometimes this occurs after the second line is drawn, so who knows!).

https://drive.google.com/file/d/0B3HJopSo_QqLUEFXbTR1UDdCQWc/view?usp=sharing

Tested in Win 8.1 FF 40.0.2

Troubleshooting information (do not edit):
Name: ‪Charges And Fields‬
URL: http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-rc.4/charges-and-fields_en.html
Version: 1.0.0-rc.4 2015-08-21 15:43:30 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"858e65ac","branch":"master"},"axon":{"sha":"5be7fe04","branch":"master"},"babel":{"sha":"2431e711","branch":"master"},"brand":{"sha":"ffae69f4","branch":"master"},"charges-and-fields":{"sha":"c610f581","branch":"1.0"},"chipper":{"sha":"9b362c00","branch":"master"},"dot":{"sha":"e34c6b2c","branch":"master"},"joist":{"sha":"a6ea86cb","branch":"master"},"kite":{"sha":"24978146","branch":"master"},"phet-core":{"sha":"8e31808c","branch":"master"},"phetcommon":{"sha":"e33e2f8c","branch":"master"},"scenery":{"sha":"3c146e8f","branch":"master"},"scenery-phet":{"sha":"1fa88998","branch":"master"},"sherpa":{"sha":"1759eade","branch":"master"},"sun":{"sha":"e400abb4","branch":"master"}}

**Comment by jonathanolson** [comment] 2016-03-31 15:49
Reproduced, looks like the sim is incorrectly adding in an offset to where it thinks the mouse/touch is (a small circle around a charge, when buggy, can be controlled if you identify another point on the screen where the sim thinks the center is).

**Comment by ariel-phet** [comment] 2016-09-06 14:13
Seems to no longer be an issue, closing

**Closed as completed by ariel-phet** 2016-09-06 14:13 UTC
Labels: type:bug, priority:5-deferred
