### ISSUE TITLE
Automated Testing Sim Error (4/5/2016 10:03 AM) C&F

### ISSUE THREAD

**Issue by phet-steele** [phetsims/charges-and-fields#78] opened 2016-04-05 17:31 UTC
requirejs + fuzzMouse:

```
Uncaught Error: Assertion failed: the second order correction is larger than the first
Error: Assertion failed: the second order correction is larger than the first
    at window.assertions.assertFunction (http://phettest.colorado.edu/assert/js/assert.js:23:13)
    at ElectricPotentialLine.inherit.getNextPositionAlongEquipotentialWithElectricPotential (http://phettest.colorado.edu/charges-and-fields/js/charges-and-fields/model/ElectricPotentialLine.js?bust=1459873260911:92:17)
    at ElectricPotentialLine.inherit.getEquipotentialPositionArray (http://phettest.colorado.edu/charges-and-fields/js/charges-and-fields/model/ElectricPotentialLine.js?bust=1459873260911:182:45)
    at new ElectricPotentialLine (http://phettest.colorado.edu/charges-and-fields/js/charges-and-fields/model/ElectricPotentialLine.js?bust=1459873260911:53:31)
    at ChargesAndFieldsModel.inherit.addElectricPotentialLine (http://phettest.colorado.edu/charges-and-fields/js/charges-and-fields/model/ChargesAndFieldsModel.js?bust=1459873260911:535:35)
    at ElectricPotentialSensorNode.PencilButton.listener (http://phettest.colorado.edu/charges-and-fields/js/charges-and-fields/view/ElectricPotentialSensorNode.js?bust=1459873260911:114:9)
    at http://phettest.colorado.edu/sun/js/buttons/PushButtonModel.js?bust=1459873260911:130:9
    at Array.forEach (native)
    at PushButtonModel.inherit.fire (http://phettest.colorado.edu/sun/js/buttons/PushButtonModel.js?bust=1459873260911:129:12)
    at http://phettest.colorado.edu/sun/js/buttons/PushButtonModel.js?bust=1459873260911:73:25
```

**Comment by veillette** [comment] 2016-08-01 16:10
This assertion was put in place to find out the behavior of the equipotential line near saddle point when the charges are put randomly (as when using fuzzMouse).  Even by running fuzzmouse for an hour I was not able to reproduce. 
Even when the assertion, is triggered, it signals that the calculations is not as precise as it could be for this very short segment of the line. In other words, hitting this assertion is not very worrisome.

**Comment by ariel-phet** [comment] 2016-08-01 16:16
Sounds good, marking won't fix and closing

**Closed as completed by ariel-phet** 2016-08-01 16:16 UTC
Labels: type:wontfix, type:automated-testing
