### ISSUE TITLE
Electric potential sensor "draw equipotential line" should be disabled if it won't add a line.

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/charges-and-fields#77] opened 2016-03-31 17:01 UTC

**Comment by veillette** [comment] 2016-08-01 16:27
ChargesAndFieldsModel has a boolean property called isPlayAreaCharged. The button should be disabled when isPlayAreCharged is true and enabled when false.

**Comment by phet-steele** [comment] 2016-08-15 15:07
Working as intended in 1.0.0-dev.17, closing.

**Closed as completed by phet-steele** 2016-08-15 15:07 UTC
Labels: dev:enhancement
