### ISSUE TITLE
Voltage "V" out of text box

### ISSUE THREAD

**Issue by BryceAG** [phetsims/charges-and-fields#101] opened 2016-08-30 17:52 UTC
Test device:
Dirac

Operating System:
OSX 10.9.5

Browser:
Safari

Problem description:
In some places when the equipotential measuring tool is placed in the center of a proton, it reads as a long number and the V is outside of the box. Occurs in full screen, maximized window, and normal window. This depends on where the proton is placed, as in some positions it will read the correct "infinity V"

Steps to reproduce:
Place a proton in the lower left quadrant, and move the equipotential measuring tool over the center of the proton. May require moving the proton to different positions, and may not be restricted to lower left quadrant.

Severity:
Lowest of the low

Screenshots:
![screen shot 2016-08-30 at 11 44 59 am](https://cloud.githubusercontent.com/assets/15327201/18100285/8081bd88-6ea7-11e6-847b-7952a11525cf.png)
Long number

![screen shot 2016-08-30 at 11 51 11 am](https://cloud.githubusercontent.com/assets/15327201/18100381/efed5754-6ea7-11e6-8634-5f88dd4a21a2.png)
correct infinity

Troubleshooting information (do not edit):
Name: ‪Charges And Fields‬
URL: http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.0-rc.6/charges-and-fields_en.html
Version: 1.0.0-rc.6 2016-08-29 22:42:57 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/537.86.1
Language: en-us
Window: 1240x620
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-8.24.17)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"1fd91832","branch":"HEAD"},"babel":{"sha":"4c934fae","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"HEAD"},"charges-and-fields":{"sha":"2fe5fbc4","branch":"HEAD"},"chipper":{"sha":"89c4a103","branch":"HEAD"},"dot":{"sha":"3f60cfcc","branch":"HEAD"},"joist":{"sha":"9c50d3f7","branch":"HEAD"},"kite":{"sha":"3b656b9a","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"83ea84c8","branch":"HEAD"},"scenery":{"sha":"0ab22ac3","branch":"HEAD"},"scenery-phet":{"sha":"d50f2282","branch":"HEAD"},"sherpa":{"sha":"5ddfccd4","branch":"HEAD"},"sun":{"sha":"4b852127","branch":"HEAD"},"tandem":{"sha":"43ebdfb3","branch":"HEAD"}}

related to phetsims/tasks#689

**Comment by ariel-phet** [comment] 2016-08-30 17:59
@andrewadare seems perhaps just a different threshold needs to be set

**Comment by ariel-phet** [comment] 2016-08-31 00:50
@BryceAG - just a reminder to also note ticket number in the test matrix (I have put it in there for you)

**Comment by andrewadare** [comment] 2016-08-31 15:36
@BryceAG this is quite a find...after half an hour of painstaking dragging, I'm unable to reproduce this on Safari. I tried positioning the charge and sensor all over, including exactly as you have it in your screenshot:
![image](https://cloud.githubusercontent.com/assets/154163/18134929/58cee156-6f5d-11e6-92b7-c661762d5847.png)

I also tried doing absurd things to produce a large potential readout (this one's on Chrome):
![image](https://cloud.githubusercontent.com/assets/154163/18134997/935f105c-6f5d-11e6-9c63-ab3ce562d035.png)
No matter what, the readout stays comfortably within the boundary.

> Steps to reproduce:
> Place a proton in the lower left quadrant, and move the equipotential measuring tool over the center 

I assume you mean the corners of the grid cells (disabled in your screenshots). I've certainly focused on those positions, but tried many other positions as well. Any further tips you can provide to reliably reproduce this would be appreciated.

**Comment by andrewadare** [comment] 2016-08-31 16:01
Here, I stacked ten positive charges, and positioned the sensor at its max readout value (on Safari):
![image](https://cloud.githubusercontent.com/assets/154163/18136188/a9c7a72e-6f61-11e6-82ed-4d53279dc2ca.png)

Still looks okay to me.

**Comment by BryceAG** [comment] 2016-08-31 17:01
I have reproduced it a couple times on Dirac, but I agree that it is very
difficult. I had to refresh the page to get it to work sometimes, so that
might help reproduce it. If it can't be reproduced on another computer then
it might just be a hardware issue.

**Comment by BryceAG** [comment] 2016-08-31 21:33
Reproduced on Dirac again, but OS X 10.10.5
![screen shot 2016-08-31 at 3 30 24 pm](https://cloud.githubusercontent.com/assets/15327201/18147034/19fc1aec-6f90-11e6-8033-d41a442ab88a.png)

**Comment by BryceAG** [comment] 2016-08-31 21:44
Also reproduced on Curie OS X 10.10.5
![screen shot 2016-08-31 at 3 35 58 pm](https://cloud.githubusercontent.com/assets/15327201/18147188/b6fcdfb6-6f90-11e6-85eb-c13ec188a304.png)

It doesn't look like a hardware issue, although I have not been able to reproduce it on Chrome, so I think it is safari specific

**Comment by pixelzoom** [comment] 2016-09-01 16:27
I spent a few minutes (during status meeting :) trying to reproduce this on my MacBook Pro (Mid-2009 model, Mac OS X 10.11.6).  I could not reproduce it with Safari or Chrome.

**Comment by samreid** [comment] 2016-09-01 16:50
I couldn't reproduce the problem in Chrome after a few minutes.  It looks like `Util.toFixed` looks like it still relies on `Number.toFixed`, so that is one possible place where the error my be creeping in.

**Comment by andrewadare** [comment] 2016-09-01 21:45
I borrowed Curie today and tried to find this bug. On that machine, I can reproduce it on  1.0.0-RC.6 fairly consistently by dragging to very specific locations.

I installed a minimal development stack on Curie and cloned the phet repos in order to do basic things like print console messages. I've been altogether unsuccessful reproducing the bug on the requirejs version of master. I can reproduce it on built versions, though.

Curie's not a very fast machine--it takes several minutes just to build this sim. Iteration cycles to simply print new debug messages are therefore awfully inefficient. I've far exceeded the time recommended by @ariel-phet to look into this. It may be time to move on with life....

**Comment by samreid** [comment] 2016-09-02 01:52
I am curious about this, wondering if 10.10.5 safari has bugs in toFixed or the elsewhere in the code under `decimalAdjust`.  It's possible for this bug to exhibit elsewhere (outside of charges-and-fields).

To avoid having to rebuild the sim, I'd recommend just building an unminified version you can tinker with.

**Comment by ariel-phet** [comment] 2016-09-02 01:56
@andrewadare perfect can be the enemy of good. This bug is worth no more time currently as it is a rare use case, and you have given it the college try.

Marking "won't fix" and unassigning (we can close once published)

**Comment by pixelzoom** [comment] 2016-09-02 16:38
Assuming it's still reproducible but @BryceAG.... Why not add some debug code that throws Error and prints relevant var values when this occurs?

**Comment by pixelzoom** [comment] 2016-09-02 17:15
@samreid makes a good point in https://github.com/phetsims/charges-and-fields/issues/101#issuecomment-244262906. 

Why not add something like this to detect the problem and print a stack track with relevant var values?

``` js
if ( voltage > 100000000 ) {
  try {
  throw new Error( 'unexpected voltage=' + voltage + 'other relevant vars: ' + ... );
  }
  catch ( e ) {
    console.log( e.message );
    console.log( e.stack );
  }
}
```

Then have @BryceAG reproduce it, and send @andrewadare  what's printed to the console.

**Comment by samreid** [comment] 2016-09-02 17:21
I like @pixelzoom's idea to detect the problem, but I don't see how printing the message and the stack trace will show the relevant var values.  We may need a screen capture of local variables.  Or we could have a developer sit down with Curie and do this.

**Comment by pixelzoom** [comment] 2016-09-02 17:24
What's preventing you from including relevant var values in the Error message?  E.g., if voltage were computed based on current and resistance:

``` js
var current = ...;
var resistance = ...;
if ( voltage > 100000000 ) {
  try {
  throw new Error( 'unexpected voltage=' + voltage + 'other relevant vars:  ' +
    ' current=' + current + ' resistance=' + resistance );
  }
  catch ( e ) {
    console.log( e.message );
    console.log( e.stack );
  }
}
```

**Comment by samreid** [comment] 2016-09-02 17:26
Oh yeah, that makes sense.  But it wouldn't be able to inspect values at other points in the stack.  (I know chrome dev tools can do this but I'm not sure about safari).

**Comment by veillette** [comment] 2017-07-07 13:25
It is present in all browsers. While working on #98 , I attempted to snap the electricPotential Sensor to the grid

If instead of snapping it directly to the grid, you snapped it to a value slightly off, say
```
 endDrag: function( event ) {
        electricPotentialSensor.positionProperty.set( electricPotentialSensor.positionProperty.get().dividedScalar(
          ChargesAndFieldsConstants.GRID_MAJOR_SPACING ).roundedSymmetric().timesScalar( ChargesAndFieldsConstants.GRID_MAJOR_SPACING ).plusXY( 0, 1e-10 ) );
     self.isUserControlledProperty.set( false );
      }
```

then you can easily reproduce this issue since the charge and the sensor will be 1e-10 position apart.
![image](https://user-images.githubusercontent.com/7633344/27959512-c3f0ad7a-62f5-11e7-9235-5d843bdb7408.png)

With a lot of dexterity (or luck) you can possibly reproduce this bug without the "SnapToGrid" feature.

If you remove the offset, the voltage displays correctly though,
![image](https://user-images.githubusercontent.com/7633344/27959565-f9d52ee8-62f5-11e7-9408-55177ad22f3c.png)

In any case, this bug is not browser specific.

**Comment by veillette** [comment] 2017-07-07 21:32
The value displayed is correct as well.  The problem lies with the layout. Even though the text has a maxWidth that is smaller than the size of the readout box, the text is only centered initially.  
Centering the text after each voltage update adresses the issue.

![image](https://user-images.githubusercontent.com/7633344/27977780-45958168-633a-11e7-8217-c7083bfc9f89.png)

**Comment by veillette** [comment] 2017-07-07 21:42
It is difficult (though not impossible) to put the charges and sensor so close.  Assigning back to @phet-steele if he would like to test his dexterity.

**Comment by phet-steele** [comment] 2017-07-18 16:31
Positive charges also look great to me! You the man, @veillette. 
![screen shot 2017-07-18 at 10 26 58 am 2](https://user-images.githubusercontent.com/5863899/28328426-cab5792c-6ba3-11e7-890f-d428f8f93757.png).

Not so sure there is anything left to do here. I suppose I'll assign to @arouinfar to sign off on this being how we handle long-string voltages.

**Comment by arouinfar** [comment] 2017-07-18 17:17
@veillette looks good! My only request would be to display the infinity symbol, rather than the word, when the sensor is snapped to the charge.

**Comment by veillette** [comment] 2017-07-26 15:44
Thanks @phet-steele for testing. Closing this issue and we will be tracking the display of the equipotential sensor in #127.

**Closed as completed by veillette** 2017-07-26 15:44 UTC
Labels: type:bug, type:wontfix
