### ISSUE TITLE
Automated testing failure

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/charges-and-fields#118] opened 2017-02-27 19:29 UTC
```
charges-and-fields : fuzz : require.js : run
Uncaught Error: Assertion failed: The CSS string is an invalid color: rgba(NaN,NaN,NaN,0.5)
Error: Assertion failed: The CSS string is an invalid color: rgba(NaN,NaN,NaN,0.5)
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1488222154261/assert/js/assert.js:21:13)
    at Function.Color.checkPaintString (https://bayes.colorado.edu/continuous-testing/snapshot-1488222154261/scenery/js/util/Color.js?bust=1488222836433:732:9)
    at Circle.setFill (https://bayes.colorado.edu/continuous-testing/snapshot-1488222154261/scenery/js/nodes/Paintable.js?bust=1488222836433:112:19)
    at Circle.set fill [as fill] (https://bayes.colorado.edu/continuous-testing/snapshot-1488222154261/scenery/js/nodes/Paintable.js?bust=1488222836433:125:34)
    at updateCircleFill (https://bayes.colorado.edu/continuous-testing/snapshot-1488222154261/charges-and-fields/js/charges-and-fields/view/ElectricPotentialSensorNode.js?bust=1488222836433:284:19)
    at Array.potentialListener (https://bayes.colorado.edu/continuous-testing/snapshot-1488222154261/charges-and-fields/js/charges-and-fields/view/ElectricPotentialSensorNode.js?bust=1488222836433:250:7)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1488222154261/axon/js/Emitter.js?bust=1488222836433:147:49)
    at Property._notifyObservers (https://bayes.colorado.edu/continuous-testing/snapshot-1488222154261/axon/js/Property.js?bust=1488222836433:176:29)
    at Property._setAndNotifyObservers (https://bayes.colorado.edu/continuous-testing/snapshot-1488222154261/axon/js/Property.js?bust=1488222836433:165:14)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1488222154261/axon/js/Property.js?bust=1488222836433:133:16)
Approximately 2/27/2017, 12:02:34 PM
```

**Comment by veillette** [comment] 2017-03-04 23:25
The likely culprit in ElectricPotentialSensorNode are the following lines

````
    /**
     * The color fill inside the circle changes according to the value of the electric potential*
     * @param {number} electricPotential
     */
    function updateCircleFill( electricPotential ) {
      circle.fill = getElectricPotentialColor( electricPotential, { transparency: 0.5 } );
    }
````

Presumably electricPotential  is not defined, passing an invalid color to the fill.  

For the record, the circle fill updates the fill color of  the crosshair electric potential tool. The electricPotential is the value of the potential at the crosshair.
If the crosshair is directly on a charge, the electric Potential is (physically) infinity.

**Comment by veillette** [comment] 2017-07-07 13:08
This needs to be addressed before #98

**Comment by veillette** [comment] 2017-07-07 21:54
I was able to reproduce using the snapToGrid feature.

It should be noted that it this assertion is not triggered when an electric potential sensor is directly on a charge.

To generate this assertions, put two positive charges and one negative charge on top of one another. Move the electric potential sensor on the composite charge.

**Comment by veillette** [comment] 2017-07-09 15:41
The problem arises when subtracting infinities (an always dangerous propositions).

The codebase was modified such that the electric potential at a given position makes a check to find if there are any charges at this position. It calculates the net charge at this position. If there is a net charge at this position, it return an electric potential of +infinity or -infinity, depending on the value of the net charge. This approach circumvents the 1/distance calculation that was the source of the problem.

**Comment by veillette** [comment] 2017-07-09 15:44
In passing, I deleted any references to getElectricPotentialChange since this method was overriden by the updateAllSensors call.  

As a result, the model doesn't depend on any 'change' for the calculation of the electric field and electric potential.

**Comment by veillette** [comment] 2017-07-09 15:52
Work done here. Closing.

**Closed as completed by veillette** 2017-07-09 15:52 UTC
Labels: type:bug, type:automated-testing
