### ISSUE TITLE
Completely overlapped charges still display E-field with direction only selected

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/charges-and-fields#46] opened 2015-06-23 17:07 UTC
Partially a question @ariel-phet, but I don't think the E-field direction should be displayed when the net charge at a point is zero.  Isn't the E-field explicitly zero?

To reproduce just overlap two charges

With out only direction selected the magnitude of the vectors are zero. No E-field is seen
![efield1](https://cloud.githubusercontent.com/assets/5631059/8312042/b5106222-1997-11e5-8254-3b0955306f4c.png)

With only direction selected
![efield2](https://cloud.githubusercontent.com/assets/5631059/8312045/b87670e6-1997-11e5-8fd8-ead82d0d91c3.png)

**Comment by veillette** [comment] 2015-06-23 17:54
Most likely the charges are not quite on top of another and it forms a (very) weak dipole. (according to the direction of the electric fields, the negative charge is slightly to the left of the positive charge).  The (yellow) electric sensor could indicate the magnitude which is most likely very small, however  there is the option to indicate the direction of the electric field irrespective of the magnitude E-field.

**Comment by orejolaphet** [comment] 2015-06-23 18:28
@bereaphysics I believe this is a bug as the "Direction only" E-field is not that of a dipole moment, also from the point you over lap the two charges, deselecting and selecting the E-field option forces all the E-field lines in to the same direction, which is definitely incorrect.

To reproduce:
Over lap two opposite charged particles so that the E-field vanishes
Select Direction only
Unselect Electric field
Select Electric field 

![efield3](https://cloud.githubusercontent.com/assets/5631059/8313906/266e20fc-19a3-11e5-9eb2-09c42b879b91.png)

**Comment by veillette** [comment] 2015-06-23 18:34
Your reasoning is sound. Your first instance might be related to a floating point error where mathematically the resulting electric field should be zero but there is not an exact cancellation due to the floating point error. Just a guess. I'll investigate it.

The sims does have some logic about not displaying the electric field direction when there is no charge on the play area. However is doesn't have the logic to handle the case where the 'effective charge' is zero.

**Comment by bryo5363** [comment] 2015-06-25 15:05
I also noticed some strange behavior with the order that you layer charges on one another. The difference between a negative then a positive charge and vice versa is kind of strange.

**Comment by veillette** [comment] 2015-06-25 15:13
@bryo5363: can you be more specific on the strangeness of the layering. As I recall there is no distinction between positive or positive charge, the last charge picked up is on top of the others

**Comment by bryo5363** [comment] 2015-06-25 15:17
Upon layering the charges in different order the directions of the vectors change. 

negative then positive
![screen shot 2015-06-25 at 9 16 12 am](https://cloud.githubusercontent.com/assets/7717368/8357959/e029b754-1b1a-11e5-8fba-1f0fcb0b7591.png)

positive then negative
![screen shot 2015-06-25 at 9 15 28 am](https://cloud.githubusercontent.com/assets/7717368/8357966/e8d38902-1b1a-11e5-9432-c73352f05f1b.png)

**Comment by veillette** [comment] 2015-06-29 15:35
This will not be addressed (yet) in release candidate 2 but we need to find a general solution for it such that it can handle all the cases where the "effective charge" is zero. As it turns out it is not so simple to solve.

**Comment by veillette** [comment] 2015-06-30 21:04
The proposal is to turn off the electric field grid when the 'effective charge' is zero.

**Comment by veillette** [comment] 2015-07-01 01:32
This commit works for up to two pairwise compensated sets. That is it is still possible to trick this commit it you have three pairs of +- charges. Since it is a very unlikely scenario I will not address it. This will be deployed on rc.3

**Comment by veillette** [comment] 2015-07-01 18:15
Once release candidate 3 is pushed this will be available for testing. The current approach does not take into account edge cases where the charges are almost but not quite on top of another. It would be possible to introduce an equalsEpsilon instead if it proves to be necessary,

**Comment by orejolaphet** [comment] 2015-07-06 18:00
@bereaphysics issue is partially fixed. For the most part no E-field is displayed when "effective charge" is zero, but weird vectors may still be displayed. I noticed this occurred only for the first time you over lap charges after opening the sim.

Here are two overlapped charges "effective charge" is zero, but a single vector is displayed.
![screen shot 2015-07-06 at 11 58 31 am](https://cloud.githubusercontent.com/assets/5631059/8529304/487532e8-23d6-11e5-8ce0-61e0a56d7d5c.png)

With direction only selected the E-field is that of a dipole.
![screen shot 2015-07-06 at 11 58 44 am](https://cloud.githubusercontent.com/assets/5631059/8529321/63f2affa-23d6-11e5-89f2-3450524a5292.png)

Here I have the "Effective charge" as zero with Voltage selected.
Note no voltage is displayed, but there is an E-field present. 
![screen shot 2015-07-06 at 12 02 59 pm](https://cloud.githubusercontent.com/assets/5631059/8529331/726d9568-23d6-11e5-87c9-ee3bac9d9cab.png)

**Comment by veillette** [comment] 2015-07-07 17:48
@orejolaphet: there is a clear dipole electric field which indicates that the charges are not on top of one another. The criterium used to turn off the electric field is  that  there is no effective charge, i.e. the charges are right on top of one another. It is preferable not to use a small delta epsilon to set the minimum distance because this delta epsilon would be completely arbitrary and would be unphysical. Since this is a binary operation, (no E-field, with E-field) this would look odd..

The main issue was that it was possible to generate fields that did not match the underlying charge configuration.
if you can generate unphysical electric fields such as 
![image](https://cloud.githubusercontent.com/assets/7633344/8552793/55bd9a4e-24ad-11e5-8d79-946bebab8e57.png)
or 
![image](https://cloud.githubusercontent.com/assets/7633344/8552971/30637592-24ae-11e5-8740-c238b901ff2b.png)

then the problem is not fixed..

**Comment by bryo5363** [comment] 2015-07-07 19:17
This issue seems to be resolved on Windows 7 Chrome 43. When the charges are layered exactly on top of one another the vectors will disappear.

**Comment by elisemorgan** [comment] 2015-07-07 19:45
It's a little bit more difficult than on a desktop, but even on an iPad (2 w/iOS 8.3) I was able to get the charges exactly on top of one another and the vectors disappeared.

**Comment by orejolaphet** [comment] 2015-09-14 19:43
This issue is no longer present for rc.4. Closing

**Comment by phet-steele** [comment] 2016-08-02 19:29
@andrewadare field lines no longer disappear with completely overlapped charges in 1.0.0-dev.15 (with Direction Only enabled). Seeing this happen on every device/browser. For phetsims/tasks#661.

**Comment by andrewadare** [comment] 2016-08-10 15:56
@phet-steele I just pushed a fix for this that works for one or two pairs in my tests. 

Martin has a [comment](https://github.com/phetsims/charges-and-fields/blob/a430d08640f24f7324a4215051fc8d627f710756/js/charges-and-fields/model/ChargesAndFieldsModel.js#L435-L441) that for three or more co-located opposite-sign pairs, it's still possible to contrive this scenario, but checking for it becomes very expensive. And I agree, we shouldn't do so much work (and take the performance hit) for such an obscure corner case.

**Comment by phet-steele** [comment] 2016-08-15 15:03
@andrewadare this works for one or two pairs in 1.0.0-dev.17. Closing.

I understand we will not address the case with 3+ pairs, but for posterity this is what can happen. The Equipotential meter is not disabled, so when trying to draw a field line, the following error is thrown:

```
Uncaught Error: Cannot normalize a zero-magnitude vector
(no stack trace)
```

**Closed as completed by phet-steele** 2016-08-15 15:03 UTC
Labels: type:bug

**Comment by phet-steele** [comment] 2016-08-24 19:57
Also introduces #88 with 3+ pairs.
