### ISSUE TITLE
Value label dragging not transmitted through state

### ISSUE THREAD

**Issue by phet-steele** [phetsims/charges-and-fields#133] opened 2017-08-25 17:26 UTC
Best demonstrated in the State wrapper here: http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.1.0-phetiodev.3/wrappers/state/state.html?sim=charges-and-fields&relativeSimPath

1. Place out a charge and create an electric potential line
2. Check "Values"
3. Drag the value label around. The drag is not transmitted to the lower sim. Clicking Launch will see the label in its original location, not the new location.

Seen on macOS 10.12.6 Chrome. For phetsims/QA/issues/37.

**Comment by samreid** [comment] 2017-08-26 06:19
Proposed fix committed, @phet-steele would you like to test on phettest or a new dev version?

**Comment by ghost** [comment] 2018-07-12 16:23
@samreid, I'm not able to reproduce @phet-steele's original issue using the link he provided on macOS 10.13.5 + Chrome 67.0.3396.99. The transmission lags a bit, but from what I understand that's to be expected. Unless @phet-steele can reproduce, I move to close this issue.

**Comment by phet-steele** [comment] 2018-07-18 17:34
I cannot test because of #148. I can't get an equipotential line to appear in the child iframe.

**Comment by ghost** [comment] 2018-07-18 17:43
Sorry, I am able to reproduce @phet-steele's original issue with the provided link. I thought he was talking about the label on the sensor, not the label on the equipotential line, which I hadn't realized could be moved.

**Comment by ghost** [comment] 2019-07-24 18:34
I'm going through old issues and I'm not sure how to proceed with this one. @samreid, do you have any suggestions?

**Comment by samreid** [comment] 2019-09-09 21:15
Unassigning until working on charges-and-fields again.

**Comment by pixelzoom** [comment] 2021-02-19 19:03
@samreid should the "ready-for-review" label be removed here?  From the comments above, it sounds like there's still future work to be done.

**Comment by samreid** [comment] 2021-02-19 23:22
I confirmed the equipotential lines can be dragged in master and transmit to the downstream state correctly, closing.

**Closed as completed by samreid** 2021-02-19 23:22 UTC
Labels: dev:phet-io, status:ready-for-review
