### ISSUE TITLE
Use title case in sim name

### ISSUE THREAD

**Issue by arouinfar** [phetsims/charges-and-fields#152] opened 2018-10-17 18:02 UTC
Related to https://github.com/phetsims/tasks/issues/953

The sim title is improperly cased, and currently reads "Charges **And** Fields"

`charges-and-fields.title` in <a href="https://github.com/phetsims/charges-and-fields/blob/master/charges-and-fields-strings_en.json#L2">charges-and-fields-strings_en.json</a>  should be updated to "Charges and Fields" next time this sim gets worked on.

**Comment by pixelzoom** [comment] 2019-07-16 18:01
Duplicate of #165, where there is more info/discussion.  Closing.

**Closed as completed by pixelzoom** 2019-07-16 18:01 UTC
Labels: type:duplicate
