### ISSUE TITLE
Assertion failed: instance not found for chargesAndFields.chargesAndFieldsScreen.model.electricFieldSensor_0.positionProperty

### ISSUE THREAD

**Issue by samreid** [phetsims/charges-and-fields#141] opened 2017-10-16 18:54 UTC
Error: Assertion failed: instance not found for chargesAndFields.chargesAndFieldsScreen.model.electricFieldSensor_0.positionProperty
    at window.assertions.assertFunction (http://localhost/assert/js/assert.js:22:13)
    at Object.getOptions (http://localhost/phet-io/js/phetio.js?bust=1508179724664:463:17)
    at Object.start (http://localhost/phet-io/js/phetioEvents.js?bust=1508179724664:128:31)
    at Property._notifyListeners (http://localhost/axon/js/Property.js?bust=1508179724664:184:65)
    at Property._setAndNotifyListeners (http://localhost/axon/js/Property.js?bust=1508179724664:178:14)
    at Property.set (http://localhost/axon/js/Property.js?bust=1508179724664:125:16)
    at Object. (http://localhost/charges-and-fields/js/charges-and-fields/model/ModelElement.js?bust=1508179724664:104:31)
    at TWEEN.Tween.update (http://localhost/sherpa/lib/Tween-r12.js:317:25)
    at Object.update (http://localhost/sherpa/lib/Tween-r12.js:74:27)
    at Sim.stepSimulation (http://localhost/joist/js/Sim.js?bust=1508179724664:851:22)

**Comment by phet-steele** [comment] 2017-10-16 22:26
@samreid @zepumph  

1. Drag a sensor to the far left of the tool box, but still over the tool box.
2. Release to start its animation "home".
3. Press Reset All before the sensor can make it home.

**Comment by zepumph** [comment] 2017-10-17 22:49
I can't reproduce this problem anymore, I think that https://github.com/phetsims/phet-io/commit/d2f32e26da210fe06fb36c9dab4b6d6a76297ff3#diff-a44b6bf8932e48586042b1e1e1d6aa8a may have addressed this. 

I am getting errors in the state wrapper though about imposible setState for some dynamic view components like sensor node. @samreid can you confirm this? I am finding these problems go away when I add `phetioState: false` to their options. I'm not sure if this is the best approach though. I expect that the problem has something to do with the dynamic state restore being done in the model, but not touching the view. I would have thought that the model side would create the right view components also.

**Comment by zepumph** [comment] 2017-10-17 23:35
Actually I'm getting some strange behavior. If I run phet-io fuzz tests (where CAF is the 5th or so down the line), I get this error consistently. If I update the tests such that CAF is first, or if I launch it in its own fuzzMouse window, then I can't reproduce. I am also unable to reproduce from @phet-steele's steps in https://github.com/phetsims/charges-and-fields/issues/141#issuecomment-337061875

**Comment by samreid** [comment] 2017-10-23 02:24
If I run Charges and Fields in the state wrapper and drag out a red particle, in the next or 2 frames later I get:

```js
SimIFrameAPI.js?bust=1508725383889:126 SimIFrameAPI Invocation Error: Error: Assertion failed: Impossible set state:
chargesAndFields.chargesAndFieldsScreen.view.chargedParticleNode_0
    at window.assertions.assertFunction (assert.js:22)
    at iterate (phetio.js?bust=1508725383889:238)
    at Object.setState (phetio.js?bust=1508725383889:255)
    at TPhETIO.implementation [as setState] (TPhETIO.js?bust=1508725383889:177)
    at Object.invoke (SimIFrameAPI.js?bust=1508725383889:262)
    at Object.handleSingleInvoke (SimIFrameAPI.js?bust=1508725383889:123)
    at Object.handleRequest (SimIFrameAPI.js?bust=1508725383889:165)
    at SimIFrameAPI.js?bust=1508725383889:282 Error: Assertion failed: Impossible set state:
chargesAndFields.chargesAndFieldsScreen.view.chargedParticleNode_0
    at window.assertions.assertFunction (http://localhost/assert/js/assert.js:22:13)
    at iterate (http://localhost/phet-io/js/phetio.js?bust=1508725383889:238:17)
    at Object.setState (http://localhost/phet-io/js/phetio.js?bust=1508725383889:255:14)
    at TPhETIO.implementation [as setState] (http://localhost/phet-io/js/types/TPhETIO.js?bust=1508725383889:177:16)
    at Object.invoke (http://localhost/phet-io/js/SimIFrameAPI.js?bust=1508725383889:262:29)
    at Object.handleSingleInvoke (http://localhost/phet-io/js/SimIFrameAPI.js?bust=1508725383889:123:28)
    at Object.handleRequest (http://localhost/phet-io/js/SimIFrameAPI.js?bust=1508725383889:165:35)
    at http://localhost/phet-io/js/SimIFrameAPI.js?bust=1508725383889:282:14
``

**Comment by zepumph** [comment] 2017-10-23 21:25
https://github.com/phetsims/charges-and-fields/issues/141#issuecomment-338531366 is different and will be handled in https://github.com/phetsims/charges-and-fields/issues/142. @samreid I think we are ready to close this issue.

**Closed as completed by zepumph** 2017-10-23 21:25 UTC
Labels: type:bug, dev:phet-io
